// Generated by CoffeeScript 1.6.3
(function() {
  var Js, View, fs,
    __hasProp = {}.hasOwnProperty,
    __extends = function(child, parent) { for (var key in parent) { if (__hasProp.call(parent, key)) child[key] = parent[key]; } function ctor() { this.constructor = child; } ctor.prototype = parent.prototype; child.prototype = new ctor(); child.__super__ = parent.prototype; return child; };

  View = require('./view').View;

  fs = require('fs');

  Js = (function(_super) {
    var src;

    __extends(Js, _super);

    src = {};

    function Js(file) {
      this.file = file;
      if (!src[this.file]) {
        src[this.file] = fs.readFileSync("" + __dirname + "/../client/" + this.file, 'utf-8');
      }
    }

    Js.prototype.render = function() {
      return src[this.file];
    };

    return Js;

  })(View);

  exports.Js = Js;

}).call(this);
