// Generated by CoffeeScript 1.6.3
(function() {
  var List, View,
    __hasProp = {}.hasOwnProperty,
    __extends = function(child, parent) { for (var key in parent) { if (__hasProp.call(parent, key)) child[key] = parent[key]; } function ctor() { this.constructor = child; } ctor.prototype = parent.prototype; child.prototype = new ctor(); child.__super__ = parent.prototype; return child; };

  View = require('./view').View;

  List = (function(_super) {
    __extends(List, _super);

    function List(posts) {
      this.posts = posts;
    }

    List.prototype.render = function() {
      var all, post;
      all = ((function() {
        var _i, _len, _ref, _results;
        _ref = this.posts;
        _results = [];
        for (_i = 0, _len = _ref.length; _i < _len; _i++) {
          post = _ref[_i];
          _results.push("<li><a href='" + post.slug + "'>" + post.title + "</a></li>");
        }
        return _results;
      }).call(this)).join('');
      return this.wrap("<ul>" + all + "</ul>");
    };

    return List;

  })(View);

  exports.List = List;

}).call(this);
