// Generated by CoffeeScript 1.6.3
(function() {
  var Controller, Static, fs, _ref,
    __hasProp = {}.hasOwnProperty,
    __extends = function(child, parent) { for (var key in parent) { if (__hasProp.call(parent, key)) child[key] = parent[key]; } function ctor() { this.constructor = child; } ctor.prototype = parent.prototype; child.prototype = new ctor(); child.__super__ = parent.prototype; return child; };

  Controller = require('../framework/lib').Controller;

  fs = require('fs');

  Static = (function(_super) {
    __extends(Static, _super);

    /*
    fs.readFile "../client/#{file}", 'utf-8', (err, data) ->
      if err then throw err
      @reponse.writeHead 200, 'Content-Type': 'text/html'
      data
    */


    function Static() {
      _ref = Static.__super__.constructor.apply(this, arguments);
      return _ref;
    }

    return Static;

  })(Controller);

  exports.Static = Static;

}).call(this);
